export const GET_RECIPES = 'GET_RECIPES'
export const GET_STATE_ID = 'GET_STATE_ID'
export const GET_RECIPE_DETAIL = 'GET_RECIPE_DETAIL' 
export const GET_RECIPE_BY_INGREDIENTS = 'GET_RECIPE_BY_INGREDIENTS'